### ISSUE TITLE
SSL Mode configuration is not working anymore with 1.1.1.RELEASE

### ISSUE THREAD

**Issue by mmenard-hmrc** [spring-projects/spring-data-r2dbc#389]
Since I have updated my project to use 1.1.1 RELEASE, I have this error : 

`Server support for SSL connection is disabled, but client was configured with SSL mode verify-full`

I have this configuration, which works with 1.1.0.RELEASE : 
```
spring:
  r2dbc:
    url: r2dbc:pool:postgresql://${DB_URL:localhost}:5432/myDb
    username: ${DB_USER:my_user}
    password: ${DB_PASSWORD:password}
    properties.sslMode: ${SSL_MODE:DISABLE}
    properties.sslRootCert: ${SSL_ROOT_CERT:rds-combined-ca-bundle.pem}
```

It seems `spring.r2dbc.properties.sslMode` configuration is ignored, it should be DISABLE, but it defaults to VERIFY-FULL. It works if I remove entirely the config around SSL. 
Any ideas ? I can't find documentation on how to configure this, at the beginning I tried to append SSL configuration to the URL, but it does not work.
